apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: npsc9j3ty-nodejs 
  janus-idp.io/tekton: npsc9j3ty-nodejs
  backstage.io/kubernetes-id: npsc9j3ty-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: npsc9j3ty-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml