apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: npsc9j3ty-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: npsc9j3ty-nodejs 
  name: npsc9j3ty-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: npsc9j3ty-nodejs 
